### ISSUE TITLE
Not working with v2.8.2

### ISSUE THREAD

**Issue by elalemanyo** [mutewinter/workflows2md#1]
Hi,
I try to use your code but is not working...

What I did:
1. Clone your repo
2. Run 'npm install'
3. Run 'node index.js ~/Dropbox/Preferences/Alfred.alfredpreferences/workflows'

Output:

```
_Generated with [workflows2md](https://github.com/mutewinter/workflows2md)._
```

Nothing more? What I am doing wrong?

Thanks!

**Comment by mutewinter** [comment]
I just tested locally with Alfred `v2.8.2` and it's still working for me. If the plist file format changed I'd expect to see an error in your output. Can you verify the `.plist` file in that folder contains the details about your plugins?

**Comment by elalemanyo** [comment]
" the .plist file in that folder", sorry but which folder are you taking about?

Thanks

**Comment by mutewinter** [comment]
This folder: `~/Dropbox/Preferences/Alfred.alfredpreferences/workflows` you had in the example above. This happens to be the location _I_ store my alfred config, but it doesn't necessarily have to be yours.

**Comment by elalemanyo** [comment]
The standard location is ~/Library/Application Support/Alfred 2/Alfred.alfredpreferences/preferences/workflows/, but in may case this .plist is empty... What can I do?

Thanks

**Comment by mutewinter** [comment]
Hm, good question. You could try updating your Alfred Preferences to choose a sync location. Here's mine as an example:

![screen shot 2016-02-08 at 2 21 16 pm](https://cloud.githubusercontent.com/assets/305901/12897816/46824856-ce6f-11e5-817c-a56e6b7af8c8.png)

Then the plist would show up in that folder structure and be able to be used with this generator.

**Comment by elalemanyo** [comment]
Thanks! now works!
Great tool!

**Comment by mutewinter** [comment]
Excellent news. Glad it's of use to you!
